## GET http://10.255.255.254:8080/users

## GET http://localhost:8080/usuario?id=1

### GET http://localhost:8080/usuario?email=codorna@coturnix.com


#  Novas versoes @GetMapping("/id/{id}") - @PathVariable

GET http://localhost:8080/usuario/id/1

###

GET http://localhost:8080/usuario/id/21




